backend:
  name: github
  repo: DaoWaBunga/daowabunga
  branch: main
  use_graphql: true
  squash_merges: true
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
open_authoring: true
collections:
  - name: "configs"
    label: "Configs"
    files:
      - name: "myteam"
        label: "myteam"
        file: "src/myteam.json"
        fields:
          - {
              label: "Items",
              name: "items",
              required: true,
              widget: "list",
              fields:
                [
                  { label: "memberName", name: "memberName", widget: "string" },
                  { label: "Image", name: "memberImage", widget: "string" },
                  {
                    label: "Description",
                    name: "memberDescription",
                    widget: "string",
                  },
                ],
            }
      - name: "myroadmap"
        label: "myroadmap"
        file: "src/myroadmap.json"
        fields:
          - {
              label: "Items",
              name: "items",
              required: true,
              widget: "list",
              fields:
                [
                  {
                    label: "sectionTitle",
                    name: "sectionTitle",
                    widget: "string",
                  },
                  {
                    label: "bullets",
                    name: "bullets",
                    widget: "list",
                    required: true,
                    fields:
                      [{ label: "bullet", name: "bullet", widget: "string" }],
                  },
                  {
                    label: "Map Location (Left / Right Alternate)",
                    name: "location",
                    widget: "string",
                  },
                ],
            }
